name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: | 
          docker-compose build

      - name: Push Docker image
        run: docker-compose push

      - name: Deploy to VDS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          IP: ${{ variables.IP }}
        run: | 
          echo "$SSH_PRIVATE_KEY" > private_key
          echo "$IP" > IP
          chmod 600 private_key
          ssh -i private_key root@IP "docker pull belovus/exchange-rates_react-nginx-app:latest"
          ssh -i private_key root@IP "docker stop exchange-rates_react-nginx-app"
          ssh -i private_key root@IP "docker start exchange-rates_react-nginx-app"
          
