name: CURRENCIES_DOCKER_BUILD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Building Docker image with tag: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: "exchange-rates_react-nginx-app"
          VERSION: ${{ env.VERSION }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          context: .
          push: true
          tags: ${{ DOCKER_USERNAME }}/${{ IMAGE_NAME }}:${{ VERSION }}

      - name: Set up SSH
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: "exchange-rates_react-nginx-app"
          VERSION: ${{ env.VERSION }}
        run: |
          ssh -t -o StrictHostKeyChecking=no ${{ VPS_USER }}@${{ VPS_HOST }} << 'EOF'
            set -e
            echo ${{ DOCKER_PASSWORD }} | docker login -u ${{ DOCKER_USERNAME }} --password-stdin
          
            docker stop ${{ IMAGE_NAME }} || true
            docker rm ${{ IMAGE_NAME }} || true
          
            docker pull ${{ DOCKER_USERNAME }}/${{ IMAGE_NAME }}:${{ VERSION }}
            docker run -d --name ${{ IMAGE_NAME }} ${{ DOCKER_USERNAME }}/${{ IMAGE_NAME }}:${{ VERSION }}
          EOF
